// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    OrderItem: typeof import('./src/components/orderItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanBadge: typeof import('vant/es')['Badge'];
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell'];
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanList: typeof import('vant/es')['List']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VanTag: typeof import('vant/es')['Tag']
  }
}

export {}
